import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from 'next/image';
import Link from 'next/link';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crypto",
  description: "Generated by create next app",
};

const menuItems = [
  { label: "Home", icon: "/images/Home.png" },
  { label: "Market", icon: "/images/Market.png" },
  { label: "Withdraw", icon: "/images/Wallet.png" },
  { label: "Asset", icon: "/images/Asset.png" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="fixed top-10 w-[1194px] left-1/2 transform -translate-x-1/2 z-50 p-5 bg-[rgba(255,255,255,0.06)] backdrop-blur-[20px] flex justify-between items-center text-white shadow-lg w-[80%] rounded-full">
          <div className="ml-8">
            <Image 
                aria-hidden
                src="/images/Logo.png"
                alt="Logo icon"
                width={36}
                height={50}
              />
          </div>
          <nav className="flex space-x-20 flex-grow justify-center">
            <Link href="/" className="hover:text-gray-300 font-inter font-normal text-2xl leading-none tracking-normal text-center">Home</Link>
            <a href="#" className="hover:text-gray-300 font-inter font-normal text-2xl leading-none tracking-normal text-center">Features</a>
            <a href="#" className="hover:text-gray-300 font-inter font-normal text-2xl leading-none tracking-normal text-center">Career</a>
          </nav>
          <div>
            <Link href="/register">
              <button className="px-12 py-4 text-black text-xl font-bold bg-[#aeaeae] rounded-[30px] hover:bg-[#8c8c8c]">
                Register
              </button>
            </Link>
          </div>
        </header>

        <main>
          {children}
        </main>

        <div className="fixed w-[758px] bottom-4 left-1/2 -translate-x-1/2 z-50">
                <div className="bg-[url('/images/Ellipse.png')] bg-cover bg-center"
                style={{
                    width: '1600px',  
                    height: '1600px', 
                    position: 'absolute',  
                    top: '50%', 
                    left: '50%', 
                    transform: 'translate(-50%, -50%)',
                  }}>
        
                </div>
                <div className="flex gap-10 px-20 py-2 backdrop-blur-xs bg-white/10 rounded-full shadow-lg h-[100px]">
                {menuItems.map((item) => (
                    <button
                    key={item.label}
                    className="flex items-center gap-2 px-8 py-2 my-auto bg-zinc-200 rounded-full text-black text-sm hover:bg-zinc-300 transition h-[48px]"
                    >
                    <Image src={item.icon} alt={item.label} width={16} height={16} />
                    <span>{item.label}</span>
                    </button>
                ))}
                </div>
            </div>
      </body>
    </html>
  );
}
